services:
  db:
    image: mysql:8.0
    container_name: voice-db
    restart: always
    environment:
      MYSQL_DATABASE: web_registration
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - voice_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: voice-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/web_registration?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_MAIL_USERNAME=${MAILTRAP_USERNAME}    
      - SPRING_MAIL_PASSWORD=${MAILTRAP_PASSWORD}
      - APP_BASE_URL=${APP_BASE_URL}

  #   - SPRING_MAIL_USERNAME=${MAIL_USERNAME}    #use when using real email account#
  #   - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}   #use when using real email account#
    restart: on-failure

volumes:
  voice_db_data: